# Generated by Django 4.2.7 on 2023-11-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_searcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='lenght',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='width',
            new_name='longitude',
        ),
    ]
